### Envoi de courriel
POST http://localhost:3000/api/send-mail
Content-Type: application/x-www-form-urlencoded

firstName=Théodore&lastName=Boucher&email=petit_chaton123%40chaton.chaton&text=Bonjour%20j%27ai%20vu%20votre%20site%20et%20je%20voudrais%20vous%20proposer%20un%20emploi%20%C3%A0%20200%20000%24%2Fann%C3%A9e


### Envoi de courriel avec vulnérabilité XSS
POST http://localhost:3000/api/send-mail
Content-Type: application/x-www-form-urlencoded

firstName=Théodore&lastName=Boucher&email=petit_chaton123%40chaton.chaton&text=%3Cscript%3Econsole.log%28%22hello%22%29%3C%2Fscript%3E
