name: Apercu Pull Request

on: pull_request

jobs:
  build:
    # Ne rien faire si la PR vient d'un autre repo
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    uses: ./.github/workflows/build.yml
    with:
      environment: Preview

  deploiement:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    needs: build
    uses: ./.github/workflows/deploiement-firebase.yml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      firebase-service-account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PAGE_WEB_E1C35 }}
