name: Génération du site web

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout du dépot
        uses: actions/checkout@v4

      - name: Installation de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Installation des dépendances
        run: npm ci

      - name: Génération du site web
        run: npm run build
        env:
          ENABLE_ANALYTICS: ${{ vars.ENABLE_ANALYTICS }}

      - name: Archivage du site généré
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
