name: Déploiement sur Firebase

on:
  workflow_call:
    inputs:
      firebase-channel-id:
        description: Le channelId à utiliser pour le déploiement firebase. Auto généré si laissé vide
        default: ""
        required: false
        type: string

    secrets:
      github-token:
        required: true
      firebase-service-account:
        required: true

jobs:
  deploiement:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du dépot
        uses: actions/checkout@v4

      - name: Obtention du site généré
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/

      - name: Déploiement sur Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.github-token }}
          firebaseServiceAccount: ${{ secrets.firebase-service-account }}
          channelId: ${{ inputs.firebase-channel-id }}
          projectId: page-web-e1c35
