name: Déploiement sur Firebase

on:
  workflow_call:
    inputs:
      firebaseChannelId:
        description: Le channelId à utiliser pour le déploiement firebase. Auto généré si laissé vide
        default: ""
        required: false
        type: string

jobs:
  deploiement:
    runs-on: ubuntu-latest
    steps:
      - name: Obtention du site généré
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/

      - name: Déploiement sur Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PAGE_WEB_E1C35 }}"
          channelId: ${{ inputs.firebaseChannelId }}
          projectId: page-web-e1c35
