name: Intégration continue

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépot
        uses: actions/checkout@v4

      - name: Installation de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Installation des dépendances
        run: npm ci

      - name: Génération du site web
        run: npm run build
